DROP TABLE experiences;
DROP TABLE countries;

CREATE TABLE `countries` (
`id` int (3) NOT NULL AUTO_INCREMENT,
`name` varchar(200) NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `experiences` (
  `profile_id` int (10) NOT NULL,
  `id` int (10) NOT NULL AUTO_INCREMENT,
  `company` varchar(200) NOT NULL,
  `company_activity` varchar(200) NOT NULL,
  `country_company` int (3) NOT NULL,
  `job_title` varchar(200) NOT NULL,
  `level` varchar(20) NOT NULL,
  `job_description` varchar(200) NOT NULL,
  `dependents` int,
  `start` DATE,
  `ending` DATE,
  `duration` varchar(200),
  `reference_contact` varchar(200) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `country_company` (`country_company`),
  CONSTRAINT `experiences_ibfk_country` FOREIGN KEY (`country_company`) REFERENCES `countries` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `countries` VALUES(1, 'Afganistán');
INSERT INTO `countries` VALUES(2, 'Islas Gland');
INSERT INTO `countries` VALUES(3, 'Albania');
INSERT INTO `countries` VALUES(4, 'Alemania');
INSERT INTO `countries` VALUES(5, 'Andorra');
INSERT INTO `countries` VALUES(6, 'Angola');
INSERT INTO `countries` VALUES(7, 'Anguilla');
INSERT INTO `countries` VALUES(8, 'Antártida');
INSERT INTO `countries` VALUES(9, 'Antigua y Barbuda');
INSERT INTO `countries` VALUES(10, 'Antillas Holandesas');
INSERT INTO `countries` VALUES(11, 'Arabia Saudí');
INSERT INTO `countries` VALUES(12, 'Argelia');
INSERT INTO `countries` VALUES(13, 'Argentina');
INSERT INTO `countries` VALUES(14, 'Armenia');
INSERT INTO `countries` VALUES(15, 'Aruba');
INSERT INTO `countries` VALUES(16, 'Australia');
INSERT INTO `countries` VALUES(17, 'Austria');
INSERT INTO `countries` VALUES(18, 'Azerbaiyán');
INSERT INTO `countries` VALUES(19, 'Bahamas');
INSERT INTO `countries` VALUES(20, 'Bahréin');
INSERT INTO `countries` VALUES(21, 'Bangladesh');
INSERT INTO `countries` VALUES(22, 'Barbados');
INSERT INTO `countries` VALUES(23, 'Bielorrusia');
INSERT INTO `countries` VALUES(24, 'Bélgica');
INSERT INTO `countries` VALUES(25, 'Belice');
INSERT INTO `countries` VALUES(26, 'Benin');
INSERT INTO `countries` VALUES(27, 'Bermudas');
INSERT INTO `countries` VALUES(28, 'Bhután');
INSERT INTO `countries` VALUES(29, 'Bolivia');
INSERT INTO `countries` VALUES(30, 'Bosnia y Herzegovina');
INSERT INTO `countries` VALUES(31, 'Botsuana');
INSERT INTO `countries` VALUES(32, 'Isla Bouvet');
INSERT INTO `countries` VALUES(33, 'Brasil');
INSERT INTO `countries` VALUES(34, 'Brunéi');
INSERT INTO `countries` VALUES(35, 'Bulgaria');
INSERT INTO `countries` VALUES(36, 'Burkina Faso');
INSERT INTO `countries` VALUES(37, 'Burundi');
INSERT INTO `countries` VALUES(38, 'Cabo Verde');
INSERT INTO `countries` VALUES(39, 'Islas Caimán');
INSERT INTO `countries` VALUES(40, 'Camboya');
INSERT INTO `countries` VALUES(41, 'Camerún');
INSERT INTO `countries` VALUES(42, 'Canadá');
INSERT INTO `countries` VALUES(43, 'República Centroafricana');
INSERT INTO `countries` VALUES(44, 'Chad');
INSERT INTO `countries` VALUES(45, 'República Checa');
INSERT INTO `countries` VALUES(46, 'Chile');
INSERT INTO `countries` VALUES(47, 'China');
INSERT INTO `countries` VALUES(48, 'Chipre');
INSERT INTO `countries` VALUES(49, 'Isla de Navidad');
INSERT INTO `countries` VALUES(50, 'Ciudad del Vaticano');
INSERT INTO `countries` VALUES(51, 'Islas Cocos');
INSERT INTO `countries` VALUES(52, 'Colombia');
INSERT INTO `countries` VALUES(53, 'Comoras');
INSERT INTO `countries` VALUES(54, 'República Democrática del Congo');
INSERT INTO `countries` VALUES(55, 'Congo');
INSERT INTO `countries` VALUES(56, 'Islas Cook');
INSERT INTO `countries` VALUES(57, 'Corea del Norte');
INSERT INTO `countries` VALUES(58, 'Corea del Sur');
INSERT INTO `countries` VALUES(59, 'Costa de Marfil');
INSERT INTO `countries` VALUES(60, 'Costa Rica');
INSERT INTO `countries` VALUES(61, 'Croacia');
INSERT INTO `countries` VALUES(62, 'Cuba');
INSERT INTO `countries` VALUES(63, 'Dinamarca');
INSERT INTO `countries` VALUES(64, 'Dominica');
INSERT INTO `countries` VALUES(65, 'República Dominicana');
INSERT INTO `countries` VALUES(66, 'Ecuador');
INSERT INTO `countries` VALUES(67, 'Egipto');
INSERT INTO `countries` VALUES(68, 'El Salvador');
INSERT INTO `countries` VALUES(69, 'Emiratos Árabes Unidos');
INSERT INTO `countries` VALUES(70, 'Eritrea');
INSERT INTO `countries` VALUES(71, 'Eslovaquia');
INSERT INTO `countries` VALUES(72, 'Eslovenia');
INSERT INTO `countries` VALUES(73, 'España');
INSERT INTO `countries` VALUES(74, 'Islas ultramarinas de Estados Unidos');
INSERT INTO `countries` VALUES(75, 'Estados Unidos');
INSERT INTO `countries` VALUES(76, 'Estonia');
INSERT INTO `countries` VALUES(77, 'Etiopía');
INSERT INTO `countries` VALUES(78, 'Islas Feroe');
INSERT INTO `countries` VALUES(79, 'Filipinas');
INSERT INTO `countries` VALUES(80, 'Finlandia');
INSERT INTO `countries` VALUES(81, 'Fiyi');
INSERT INTO `countries` VALUES(82, 'Francia');
INSERT INTO `countries` VALUES(83, 'Gabón');
INSERT INTO `countries` VALUES(84, 'Gambia');
INSERT INTO `countries` VALUES(85, 'Georgia');
INSERT INTO `countries` VALUES(86, 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO `countries` VALUES(87, 'Ghana');
INSERT INTO `countries` VALUES(88, 'Gibraltar');
INSERT INTO `countries` VALUES(89, 'Granada');
INSERT INTO `countries` VALUES(90, 'Grecia');
INSERT INTO `countries` VALUES(91, 'Groenlandia');
INSERT INTO `countries` VALUES(92, 'Guadalupe');
INSERT INTO `countries` VALUES(93, 'Guam');
INSERT INTO `countries` VALUES(94, 'Guatemala');
INSERT INTO `countries` VALUES(95, 'Guayana Francesa');
INSERT INTO `countries` VALUES(96, 'Guinea');
INSERT INTO `countries` VALUES(97, 'Guinea Ecuatorial');
INSERT INTO `countries` VALUES(98, 'Guinea-Bissau');
INSERT INTO `countries` VALUES(99, 'Guyana');
INSERT INTO `countries` VALUES(100, 'Haití');
INSERT INTO `countries` VALUES(101, 'Islas Heard y McDonald');
INSERT INTO `countries` VALUES(102, 'Honduras');
INSERT INTO `countries` VALUES(103, 'Hong Kong');
INSERT INTO `countries` VALUES(104, 'Hungría');
INSERT INTO `countries` VALUES(105, 'India');
INSERT INTO `countries` VALUES(106, 'Indonesia');
INSERT INTO `countries` VALUES(107, 'Irán');
INSERT INTO `countries` VALUES(108, 'Iraq');
INSERT INTO `countries` VALUES(109, 'Irlanda');
INSERT INTO `countries` VALUES(110, 'Islandia');
INSERT INTO `countries` VALUES(111, 'Israel');
INSERT INTO `countries` VALUES(112, 'Italia');
INSERT INTO `countries` VALUES(113, 'Jamaica');
INSERT INTO `countries` VALUES(114, 'Japón');
INSERT INTO `countries` VALUES(115, 'Jordania');
INSERT INTO `countries` VALUES(116, 'Kazajstán');
INSERT INTO `countries` VALUES(117, 'Kenia');
INSERT INTO `countries` VALUES(118, 'Kirguistán');
INSERT INTO `countries` VALUES(119, 'Kiribati');
INSERT INTO `countries` VALUES(120, 'Kuwait');
INSERT INTO `countries` VALUES(121, 'Laos');
INSERT INTO `countries` VALUES(122, 'Lesotho');
INSERT INTO `countries` VALUES(123, 'Letonia');
INSERT INTO `countries` VALUES(124, 'Líbano');
INSERT INTO `countries` VALUES(125, 'Liberia');
INSERT INTO `countries` VALUES(126, 'Libia');
INSERT INTO `countries` VALUES(127, 'Liechtenstein');
INSERT INTO `countries` VALUES(128, 'Lituania');
INSERT INTO `countries` VALUES(129, 'Luxemburgo');
INSERT INTO `countries` VALUES(130, 'Macao');
INSERT INTO `countries` VALUES(131, 'ARY Macedonia');
INSERT INTO `countries` VALUES(132, 'Madagascar');
INSERT INTO `countries` VALUES(133, 'Malasia');
INSERT INTO `countries` VALUES(134, 'Malawi');
INSERT INTO `countries` VALUES(135, 'Maldivas');
INSERT INTO `countries` VALUES(136, 'Malí');
INSERT INTO `countries` VALUES(137, 'Malta');
INSERT INTO `countries` VALUES(138, 'Islas Malvinas');
INSERT INTO `countries` VALUES(139, 'Islas Marianas del Norte');
INSERT INTO `countries` VALUES(140, 'Marruecos');
INSERT INTO `countries` VALUES(141, 'Islas Marshall');
INSERT INTO `countries` VALUES(142, 'Martinica');
INSERT INTO `countries` VALUES(143, 'Mauricio');
INSERT INTO `countries` VALUES(144, 'Mauritania');
INSERT INTO `countries` VALUES(145, 'Mayotte');
INSERT INTO `countries` VALUES(146, 'México');
INSERT INTO `countries` VALUES(147, 'Micronesia');
INSERT INTO `countries` VALUES(148, 'Moldavia');
INSERT INTO `countries` VALUES(149, 'Mónaco');
INSERT INTO `countries` VALUES(150, 'Mongolia');
INSERT INTO `countries` VALUES(151, 'Montserrat');
INSERT INTO `countries` VALUES(152, 'Mozambique');
INSERT INTO `countries` VALUES(153, 'Myanmar');
INSERT INTO `countries` VALUES(154, 'Namibia');
INSERT INTO `countries` VALUES(155, 'Nauru');
INSERT INTO `countries` VALUES(156, 'Nepal');
INSERT INTO `countries` VALUES(157, 'Nicaragua');
INSERT INTO `countries` VALUES(158, 'Níger');
INSERT INTO `countries` VALUES(159, 'Nigeria');
INSERT INTO `countries` VALUES(160, 'Niue');
INSERT INTO `countries` VALUES(161, 'Isla Norfolk');
INSERT INTO `countries` VALUES(162, 'Noruega');
INSERT INTO `countries` VALUES(163, 'Nueva Caledonia');
INSERT INTO `countries` VALUES(164, 'Nueva Zelanda');
INSERT INTO `countries` VALUES(165, 'Omán');
INSERT INTO `countries` VALUES(166, 'Países Bajos');
INSERT INTO `countries` VALUES(167, 'Pakistán');
INSERT INTO `countries` VALUES(168, 'Palau');
INSERT INTO `countries` VALUES(169, 'Palestina');
INSERT INTO `countries` VALUES(170, 'Panamá');
INSERT INTO `countries` VALUES(171, 'Papúa Nueva Guinea');
INSERT INTO `countries` VALUES(172, 'Paraguay');
INSERT INTO `countries` VALUES(173, 'Perú');
INSERT INTO `countries` VALUES(174, 'Islas Pitcairn');
INSERT INTO `countries` VALUES(175, 'Polinesia Francesa');
INSERT INTO `countries` VALUES(176, 'Polonia');
INSERT INTO `countries` VALUES(177, 'Portugal');
INSERT INTO `countries` VALUES(178, 'Puerto Rico');
INSERT INTO `countries` VALUES(179, 'Qatar');
INSERT INTO `countries` VALUES(180, 'Reino Unido');
INSERT INTO `countries` VALUES(181, 'Reunión');
INSERT INTO `countries` VALUES(182, 'Ruanda');
INSERT INTO `countries` VALUES(183, 'Rumania');
INSERT INTO `countries` VALUES(184, 'Rusia');
INSERT INTO `countries` VALUES(185, 'Sahara Occidental');
INSERT INTO `countries` VALUES(186, 'Islas Salomón');
INSERT INTO `countries` VALUES(187, 'Samoa');
INSERT INTO `countries` VALUES(188, 'Samoa Americana');
INSERT INTO `countries` VALUES(189, 'San Cristóbal y Nevis');
INSERT INTO `countries` VALUES(190, 'San Marino');
INSERT INTO `countries` VALUES(191, 'San Pedro y Miquelón');
INSERT INTO `countries` VALUES(192, 'San Vicente y las Granadinas');
INSERT INTO `countries` VALUES(193, 'Santa Helena');
INSERT INTO `countries` VALUES(194, 'Santa Lucía');
INSERT INTO `countries` VALUES(195, 'Santo Tomé y Príncipe');
INSERT INTO `countries` VALUES(196, 'Senegal');
INSERT INTO `countries` VALUES(197, 'Serbia y Montenegro');
INSERT INTO `countries` VALUES(198, 'Seychelles');
INSERT INTO `countries` VALUES(199, 'Sierra Leona');
INSERT INTO `countries` VALUES(200, 'Singapur');
INSERT INTO `countries` VALUES(201, 'Siria');
INSERT INTO `countries` VALUES(202, 'Somalia');
INSERT INTO `countries` VALUES(203, 'Sri Lanka');
INSERT INTO `countries` VALUES(204, 'Suazilandia');
INSERT INTO `countries` VALUES(205, 'Sudáfrica');
INSERT INTO `countries` VALUES(206, 'Sudán');
INSERT INTO `countries` VALUES(207, 'Suecia');
INSERT INTO `countries` VALUES(208, 'Suiza');
INSERT INTO `countries` VALUES(209, 'Surinam');
INSERT INTO `countries` VALUES(210, 'Svalbard y Jan Mayen');
INSERT INTO `countries` VALUES(211, 'Tailandia');
INSERT INTO `countries` VALUES(212, 'Taiwán');
INSERT INTO `countries` VALUES(213, 'Tanzania');
INSERT INTO `countries` VALUES(214, 'Tayikistán');
INSERT INTO `countries` VALUES(215, 'Territorio Británico del Océano Índico');
INSERT INTO `countries` VALUES(216, 'Territorios Australes Franceses');
INSERT INTO `countries` VALUES(217, 'Timor Oriental');
INSERT INTO `countries` VALUES(218, 'Togo');
INSERT INTO `countries` VALUES(219, 'Tokelau');
INSERT INTO `countries` VALUES(220, 'Tonga');
INSERT INTO `countries` VALUES(221, 'Trinidad y Tobago');
INSERT INTO `countries` VALUES(222, 'Túnez');
INSERT INTO `countries` VALUES(223, 'Islas Turcas y Caicos');
INSERT INTO `countries` VALUES(224, 'Turkmenistán');
INSERT INTO `countries` VALUES(225, 'Turquía');
INSERT INTO `countries` VALUES(226, 'Tuvalu');
INSERT INTO `countries` VALUES(227, 'Ucrania');
INSERT INTO `countries` VALUES(228, 'Uganda');
INSERT INTO `countries` VALUES(229, 'Uruguay');
INSERT INTO `countries` VALUES(230, 'Uzbekistán');
INSERT INTO `countries` VALUES(231, 'Vanuatu');
INSERT INTO `countries` VALUES(232, 'Venezuela');
INSERT INTO `countries` VALUES(233, 'Vietnam');
INSERT INTO `countries` VALUES(234, 'Islas Vírgenes Británicas');
INSERT INTO `countries` VALUES(235, 'Islas Vírgenes de los Estados Unidos');
INSERT INTO `countries` VALUES(236, 'Wallis y Futuna');
INSERT INTO `countries` VALUES(237, 'Yemen');
INSERT INTO `countries` VALUES(238, 'Yibuti');
INSERT INTO `countries` VALUES(239, 'Zambia');
INSERT INTO `countries` VALUES(240, 'Zimbabue');